apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  ports:
  - nodePort: 30345 # Exposes this port to the outside world. Use 'minikube ip' to get the ip address of the cluster
                    # Then use http://<ip from minikube ip>:<port> to access the service
    port: 80 # exposes this port within Kubernetes environment
    name: http
    targetPort: 8080 # this is the port that should be exposed by the container
  selector:
    app: helloworld
  type: LoadBalancer  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
      tier: api
  template:
    metadata:
      labels:
        app: helloworld
        tier: api
    spec:
      containers:
      - name: helloworld
        image: neranjana/helloworld:1.0
        ports:
        - containerPort: 8080 # lets trafic through this port to the container. Application inside should be listening to this